const fs = require('fs');
let c = fs.readFileSync('frontend-react/src/js/app.js', 'utf8');

c = c.replace(/case 'document-remove':\{const doc=db\.documents\.find\(d=>d\.id===id&&d\.studentId===u\.id\);if\(!doc\)throw new Error\('Document unavailable\.'\);showModal\('Remove document\?',`<p>Remove <strong>\$\{e\(doc\.name\)\}<\/strong> from this browser's demo storage\?<\/p>`,async\(\)=>\{await fileOp\('delete',id\);db\.documents=db\.documents\.filter\(d=>d\.id!==id\);save\(\);toast\('Document removed\.'\);\},'Remove document'\);return;\}/,
  "case 'document-remove':{const doc=db.documents.find(d=>d.id===id&&d.studentId===u.id);if(!doc)throw new Error('Document unavailable.');showModal('Remove document?',`<p>Remove <strong>${e(doc.name)}</strong>?</p>`,async()=>{if(doc.filePath){if(!uuidRegex.test(u.id))throw new Error('Demo records cannot be saved to the live database.');const {error:sErr}=await supabase.storage.from('documents').remove([doc.filePath]);if(sErr)throw new Error(sErr.message);const {error:dbErr,data:del}=await supabase.from('documents').delete().eq('id',doc.id).select();if(dbErr||!del||!del.length)throw new Error(dbErr?dbErr.message:'Delete failed.');await syncRemote(supabase,db);}else{await fileOp('delete',id);db.documents=db.documents.filter(d=>d.id!==id);}save();toast('Document removed.');},'Remove document');return;}");

c = c.replace(/case 'file-download':\{const doc=db\.documents\.find\(d=>d\.id===id&&d\.studentId===u\.id\)\|\|visibleIncidents\(u\)\.find\(i=>i\.evidence\?\.id===id\)\?\.evidence;if\(!doc\)throw new Error\('File is outside your access scope\.'\);const file=await fileOp\('get',id\);if\(!file\)throw new Error\('This file is no longer in browser storage\. Please upload it again\.'\);download\(doc\.name,file\);return;\}/,
  "case 'file-download':{const doc=db.documents.find(d=>d.id===id&&d.studentId===u.id)||visibleIncidents(u).find(i=>i.evidence?.id===id)?.evidence;if(!doc)throw new Error('File is outside your access scope.');if(doc.filePath){const {data,error}=await supabase.storage.from('documents').createSignedUrl(doc.filePath,60);if(error||!data)throw new Error('Download failed.');const a=document.createElement('a');a.href=data.signedUrl;a.download=doc.name;a.click();}else{const file=await fileOp('get',id);if(!file)throw new Error('This file is no longer in browser storage. Please upload it again.');download(doc.name,file);}return;}");

c = c.replace(/legacy:\{applicationDetail,editJob,studentDetail,incidentNew,incidentDetail,evaluate,logDetail,editHTE,userNew,importUsers,documentUpload,assignPlacementRemote\}/,
  "legacy:{applicationDetail,editJob,studentDetail,incidentNew,incidentDetail,evaluate,logDetail,editHTE,userNew,importUsers,documentUpload,assignPlacementRemote,getSignedUrl:async(p)=>(await supabase.storage.from('documents').createSignedUrl(p,60)).data?.signedUrl}");

fs.writeFileSync('frontend-react/src/js/app.js', c);
